### ISSUE TITLE
The `Opt<null>` type is not supported.

### ISSUE THREAD

**Issue by dansteren** [demergent-labs/kybra#219]
If you have a method that returns an `Opt<string>` you can `return null` or `return ""` and both are valid values. But if you have a method that returns `Opt<null>` you can never return an opt with a null inside. You can currently only `return null`. We should be able to return both `null` (to indicate that there wasn't anything in the result, as well as some `Opt(null)` thing (syntax to be decided later) to indicate that there is something there, and the value is a `null`.

**Comment by lastmjs** [comment]
We are closing this issue anticipating an entire rearchitecture of Kybra similar to what we have done with Azle. This removes most of the compiler architecture as it is. We believe that this issue no longer applies to the new planned architecture.

In case our rearchitecture is not successful, or we otherwise need to find these closed issues, the search term KYBRA_REARCHITECTURE can be used.
