### ISSUE TITLE
Update python cli (not rust cli) to display new results

### ISSUE THREAD

**Issue by bdemann** [demergent-labs/kybra#277]
The CDK Framework is now going to return errors instead of just having the CLI panick on step 2. We need to change the python part of the CLI to adapt to the fact that the rust CLI will return a non-zero status code and dump a list of errors/warnings to stderr. It then reads all that and displays it nicely to the user. Maybe with the 💣 emoji, maybe in red text, maybe not red... figuring all that out so it looks good.

What's not in scope: actually updating the rust part of kybra to deal with handling the results from the CDK Framework.

- [ ] Experiment with grabbing the type not found errors from the TypeScript compiler
  - [ ] If this is easy just go for it
  - [ ] Convert the errors into a format that the Rust code can display to the user
- [ ] Format all Python errors in the rust format
    - [ ] Write a simple rust program that takes in the errors and calls the annotate snippets library.
- [ ] Get colors to actually work (from the Rust side too)

**Comment by lastmjs** [comment]
We are closing this issue anticipating an entire rearchitecture of Kybra similar to what we have done with Azle. This removes most of the compiler architecture as it is. We believe that this issue no longer applies to the new planned architecture.

In case our rearchitecture is not successful, or we otherwise need to find these closed issues, the search term KYBRA_REARCHITECTURE can be used.
