### ISSUE TITLE
Recombine update and query generate match arm code

### ISSUE THREAD

**Issue by bdemann** [demergent-labs/kybra#278]
during the cdk refactor, for a time we split up the query and update methods, later we make the QueryOrUpdateMethod so that they could be worked on together, but in Kybra they are still operated on separately and the results get combined again after they are token streams. We can now recombine these instances with the QueryOrUpdateMethod so that we only need to generate the token stream once.

For example in reply.rs we have 
```rust
fn generate_update_match_arm(update_method: &UpdateMethod) -> TokenStream {
    let name = &update_method.name;
    let return_type = update_method
        .create_return_type_annotation(&crate::get_python_keywords(), &update_method.name);
    quote!(
        #name => {
            let reply_value: #return_type = reply_value_py_object_ref.try_from_vm_value(vm).unwrap();
            ic_cdk::api::call::reply((reply_value,)).try_into_vm_value(vm).unwrap()
        }
    )
}

fn generate_query_match_arm(query_method: &QueryMethod) -> TokenStream {
    let name = &query_method.name;
    let return_type = query_method
        .create_return_type_annotation(&crate::get_python_keywords(), &query_method.name);
    quote!(
        #name => {
            let reply_value: #return_type = reply_value_py_object_ref.try_from_vm_value(vm).unwrap();
            ic_cdk::api::call::reply((reply_value,)).try_into_vm_value(vm).unwrap()
        }
    )
}
```

**Comment by lastmjs** [comment]
We are closing this issue anticipating an entire rearchitecture of Kybra similar to what we have done with Azle. This removes most of the compiler architecture as it is. We believe that this issue no longer applies to the new planned architecture.

In case our rearchitecture is not successful, or we otherwise need to find these closed issues, the search term KYBRA_REARCHITECTURE can be used.
