### ISSUE TITLE
do the get get_stmt_kinds call in the PyAst::new() so that we can access the results all the time 

### ISSUE THREAD

**Issue by bdemann** [demergent-labs/kybra#308]
instead of running get_stmt_kinds over and over again

**Comment by lastmjs** [comment]
We are closing this issue anticipating an entire rearchitecture of Kybra similar to what we have done with Azle. This removes most of the compiler architecture as it is. We believe that this issue no longer applies to the new planned architecture.

In case our rearchitecture is not successful, or we otherwise need to find these closed issues, the search term KYBRA_REARCHITECTURE can be used.
