### ISSUE TITLE
Consider allowing Services without methods

### ISSUE THREAD

**Issue by dansteren** [demergent-labs/kybra#379]
Right now we require services to have at least one method. We should maybe allow services without any. Kinda pointless, but who are we to judge.

**Comment by lastmjs** [comment]
We are closing this issue anticipating an entire rearchitecture of Kybra similar to what we have done with Azle. This removes most of the compiler architecture as it is. We believe that this issue no longer applies to the new planned architecture.

In case our rearchitecture is not successful, or we otherwise need to find these closed issues, the search term KYBRA_REARCHITECTURE can be used.
