### ISSUE TITLE
Research how to create symbol table in Python

### ISSUE THREAD

**Issue by bdemann** [demergent-labs/kybra#395]

**Comment by bdemann** [comment]
We are putting this on hold right now. It seems like it's going to be pretty involved, we have put out some questions on the pyright repo discussions to see if someone there will be able to guide us. https://github.com/microsoft/pyright/discussions/5438

**Comment by lastmjs** [comment]
We are closing this issue anticipating an entire rearchitecture of Kybra similar to what we have done with Azle. This removes most of the compiler architecture as it is. We believe that this issue no longer applies to the new planned architecture.

In case our rearchitecture is not successful, or we otherwise need to find these closed issues, the search term KYBRA_REARCHITCTURE can be used.
