### ISSUE TITLE
implement symbol table in kybra (stage 2)

### ISSUE THREAD

**Issue by bdemann** [demergent-labs/kybra#397]
Note that this step does not require stage 1 to be complete. We know how to do this right now and it has no blockers

**Comment by lastmjs** [comment]
We are closing this issue anticipating an entire rearchitecture of Kybra similar to what we have done with Azle. This removes most of the compiler architecture as it is. We believe that this issue no longer applies to the new planned architecture.

In case our rearchitecture is not successful, or we otherwise need to find these closed issues, the search term KYBRA_REARCHITCTURE can be used.
