### ISSUE TITLE
Support lists of lists

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/kybra#58]
Our Rust TryFrom and TryInto vm value conversion code does not have a general solution for lists of lists (vectors of vectors). This same problem exists in Azle.

**Comment by bdemann** [comment]
This ticket is essentially the same as https://github.com/demergent-labs/azle/issues/786 I will block that ticket and do all of the work for kybra first, then use the same solution for azle.

**Comment by bdemann** [comment]
I just worked with @lastmjs to walk through what is causing this issue. Here is everything that I learned.

I started with a very simple example to try and understand the issue better.

``` Rust
trait ToCoolString {
    fn to_cool_string(&self) -> String;
}

impl ToCoolString for String {
    fn to_cool_string(&self) -> String{
        format!("cool {}", self)
    }
}

impl<T> ToCoolString for Vec<T> where T: ToCoolString {
    fn to_cool_string(&self) -> String {
        let cool = self.iter().fold(String::new(), |cool_string, item| {
            format!("{}{}, ", cool_string, item.to_cool_string())
        });
        cool[..cool.len() - 2].to_string()
    }
}
```

So here we have simple example where we have a trait for a basic type and then we can easily make a trait for a list of things that implement that trait. And with this example you have have any level of depth that you want.

But our try_from_vm_value is a little more complicated because the return value is no always just String. 

Here is a little more complicated example to show that working.

```Rust
trait ToCool<T> {
    fn to_cool(&self) -> T;
}

impl ToCool<String> for String {
    fn to_cool(&self) -> String {
        format!("{} is cool", self)
    }
}

impl ToCool<bool> for bool {
    fn to_cool(&self) -> bool {
        true
    }
}

impl ToCool<u8> for u8 {
    fn to_cool(&self) -> u8 {
        if self % 2 == 0 {
            return *self
        }
        return self + 1
    }
}

impl ToCool<u16> for u16 {
    fn to_cool(&self) -> u16 {
        if self % 2 == 0 {
            return *self
        }
        return self + 1
    }
}

impl<T> ToCool<Vec<T>> for Vec<T>
where
    T: ToCool<T>,
{
    fn to_cool(&self) -> Vec<T> {
        self.iter().map(|not_cool| not_cool.to_cool()).collect()
    }
}
```

That's closer and it still scales to any depth of list of lists.

This is where @lastmjs came in and told me that the problem was a little more complicated still.

The blob type is an alias for a Vec<u8> and there are certain optimizations that we can and want to do for blobs that we cannot do for vecs of other types.

And when you try to add an implementation specifically for blobs or lists of blobs then we get a conflicting definition error
```Rust
type blob = Vec<u8>;

impl ToCool<blob> for blob {
    fn to_cool(&self) -> blob {
        vec![1,2,3,4,5,6]
    }
}
```
```
conflicting implementations of trait `ToCool<std::vec::Vec<u8>>`
```

The way we are currently handling this issue is by explicitly defining an implementation of the traits for a vec of each type, but currently we only have it written out for a list of the type and not a list of lists or a list of lists of lists of that type.

One idea that will almost certainly work is to write a macro that will define the implementation of all of the depths we think will be needed. We're thinking that a list of lists of lists of lists of lists of a type should be sufficient (or in other words 5 deep) and then if someone comes a long with a reasonable use case for deeper we can increase the depth at that time.

We briefly explored negative bounds based on a suggestion from ChatGPT, but it turns out, as far as we can tell, rust doesn't actually support negative bounds and ChatGPT was trained on data for a world in the future or in a fantasy. ;P

But it did give me a crazy idea. If we already have to explicitly enumerate all of the types anyways why don't we make a trait and assign it to every type except for u8. Then we can use a positive bounds and we will be off to the races.

```Rust
trait NotU8 {

}

trait IsU8 {

}

impl IsU8 for u8 {

}

impl NotU8 for String {

}

impl NotU8 for u16 {

}

impl NotU8 for () {

}

impl<T> NotU8 for Vec<T> {

}

impl<T> ToCool<Vec<T>> for Vec<T>
where
    T: ToCool<T>,
    T: NotU8
{
    fn to_cool(&self) -> Vec<T> {
        self.iter().map(|not_cool| not_cool.to_cool()).collect()
    }
}

type blob = Vec<u8>;

impl ToCool<blob> for blob {
    fn to_cool(&self) -> blob {
        vec![1,2,3,4,5,6]
    }
}
```

At least in the simple example above, it worked out, so I'm going to try it out for try_from_vm_value and try_into_vm_value and see what happens. Worst case scenario we go back to the macros.
